sudo: required
services:
  - docker

before_install:
  - docker build -t NirmalMarisetty/docker-react -f Dockerfile.dev .

script:
  - docker run NirmalMarisetty/docker-react npm run test -- --coverage
  

